# Generated by Django 4.2.5 on 2023-09-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jenis_pengiriman',
            fields=[
                ('id_jenis_pengiriman', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis_pengiriman', models.CharField(max_length=50)),
                ('tarif_pengiriman', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id_karyawan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_karyawan_kurir', models.CharField(max_length=50)),
                ('no_hp_karyawan_kurir', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paket',
            fields=[
                ('id_paket', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_paket', models.CharField(max_length=50)),
                ('harga_paket', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=250)),
                ('no_hp_pelanggan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pengiriman',
            fields=[
                ('id_pengiriman', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pengiriman', models.DateField()),
                ('id_jenis_pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grill.jenis_pengiriman')),
                ('id_karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grill.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='pemesanan',
            fields=[
                ('id_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_paket', models.IntegerField()),
                ('tanggal_pemesanan', models.DateField()),
                ('id_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grill.paket')),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grill.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='detail_pemesanan',
            fields=[
                ('id_detail_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('id_pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grill.pemesanan')),
                ('id_pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grill.karyawan')),
            ],
        ),
    ]
