# Generated by Django 4.2.5 on 2023-10-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_pemesanan',
            name='id_pengiriman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grill.pengiriman'),
        ),
    ]
